// src/config/s3.js
const AWS = require('aws-sdk');
const multer = require('multer');
const multerS3 = require('multer-s3');

const s3 = new AWS.S3({
  accessKeyId:     process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  region:          process.env.AWS_REGION || 'us-east-1',
});

const upload = multer({
  storage: multerS3({
    s3,
    bucket: process.env.AWS_S3_BUCKET || 'educore-uploads',
    acl: 'private',
    key: (req, file, cb) => {
      const folder = req.uploadFolder || 'misc';
      const ext = file.originalname.split('.').pop();
      const name = `${folder}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
      cb(null, name);
    },
    contentType: multerS3.AUTO_CONTENT_TYPE,
  }),
  limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB
  fileFilter: (_req, file, cb) => {
    const allowed = ['application/pdf','image/jpeg','image/png','image/webp','application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
    cb(null, allowed.includes(file.mimetype));
  },
});

/**
 * Upload a buffer directly to S3 (for PDFs generated by Puppeteer)
 */
async function uploadBuffer(buffer, key, contentType = 'application/pdf') {
  const params = {
    Bucket: process.env.AWS_S3_BUCKET || 'educore-uploads',
    Key: key,
    Body: buffer,
    ContentType: contentType,
  };
  const result = await s3.upload(params).promise();
  return result.Location;
}

/**
 * Generate a signed URL for private file access
 */
function getSignedUrl(key, expiresIn = 3600) {
  return s3.getSignedUrl('getObject', {
    Bucket: process.env.AWS_S3_BUCKET,
    Key: key,
    Expires: expiresIn,
  });
}

module.exports = { s3, upload, uploadBuffer, getSignedUrl };
